# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-21 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wakeup',
            name='wakeupmood',
            field=models.CharField(default='good', max_length=100),
        ),
    ]
