# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-24 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_wakeup_wakeupmood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wakeup',
            name='wakeupmood',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='wakeup',
            name='wakeuptime',
            field=models.DateTimeField(),
        ),
    ]
