# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-14 20:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='wakeup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wakeuptime_plan', models.DateTimeField()),
                ('wakeuptime', models.DateTimeField()),
                ('wakeupmood', models.BooleanField()),
            ],
        ),
    ]
