# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-25 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Morning', '0003_auto_20161124_1827'),
    ]

    operations = [
        migrations.CreateModel(
            name='MLight_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mlight', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Light_State',
        ),
    ]
